package view;

public enum GameState {
    PUTFIRSTINSECT, 
    PUTFIRSTMUSHROOM, 
    WAITFUNGALCOMMAND, 
    WAITINSECTCOMMAND,
    SELECTINSECTFORMOVE, MOVEINSECT,
    SELECTINSECTFORCUT, CUTTHREAD,
    BRANCHTHREAD,
    EATINSECT,
    SELECTMUSHROOMFORSHOOT, SHOOTSPORE,
    GROWMUSHROOM
}
